package com.catalog.model;

import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Classgroup generated by hbm2java
 */
public class ClassGroup implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Specialization specialization;
	private String name;
	private int yearOfStudy;
	private Teacher teacher = new Teacher();

	private Set<SubjectTeacherForClass> subjectteacherforclasses = new HashSet<SubjectTeacherForClass>(
			0);
	private Set<Student> students = new HashSet<Student>(0);

	public ClassGroup() {
	}

	public ClassGroup(Specialization specialization, String name,
			int yearOfStudy) {
		this.specialization = specialization;
		this.name = name;
		this.yearOfStudy = yearOfStudy;
	}

	public ClassGroup(Specialization specialization, String name,
			int yearOfStudy, Teacher teacher,
			Set<SubjectTeacherForClass> subjectteacherforclasses,
			Set<Student> students) {
		this.specialization = specialization;
		this.name = name;
		this.yearOfStudy = yearOfStudy;
		this.teacher = teacher;
		this.subjectteacherforclasses = subjectteacherforclasses;
		this.students = students;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Specialization getSpecialization() {
		return this.specialization;
	}

	public void setSpecialization(Specialization specialization) {
		this.specialization = specialization;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getYearOfStudy() {
		return this.yearOfStudy;
	}

	public void setYearOfStudy(int yearOfStudy) {
		this.yearOfStudy = yearOfStudy;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public Set<SubjectTeacherForClass> getSubjectteacherforclasses() {
		return this.subjectteacherforclasses;
	}

	public void setSubjectteacherforclasses(
			Set<SubjectTeacherForClass> subjectteacherforclasses) {
		this.subjectteacherforclasses = subjectteacherforclasses;
	}

	public Set<Student> getStudents() {
		return this.students;
	}

	@JsonIgnore
	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
