package com.catalog.model;

import java.util.Date;

/**
 * Studentmark generated by hbm2java
 */
public class StudentMark implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private SubjectTeacherForClass subjectTeacherForClass;
	private Student student;
	private int mark;
	private boolean finalExam;
	private Date date;
	private Semester semester;

	public StudentMark() {
	}

	public StudentMark(SubjectTeacherForClass subjectTeacherForClass,
			Student student, int mark, boolean finalExam, Date date) {
		this.subjectTeacherForClass = subjectTeacherForClass;
		this.student = student;
		this.mark = mark;
		this.finalExam = finalExam;
		this.date = date;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public SubjectTeacherForClass getSubjectteacherforclass() {
		return this.subjectTeacherForClass;
	}

	public void setSubjectteacherforclass(
			SubjectTeacherForClass subjectTeacherForClass) {
		this.subjectTeacherForClass = subjectTeacherForClass;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public int getMark() {
		return this.mark;
	}

	public void setMark(int mark) {
		this.mark = mark;
	}

	public boolean isFinalExam() {
		return this.finalExam;
	}

	public void setFinalExam(boolean finalExam) {
		this.finalExam = finalExam;
	}

	public Semester getSemester() {
		return this.semester;
	}

	public void setSemester(Semester semester) {
		this.semester = semester;
	}

}
