package com.catalog.model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonIgnore;


/**
 * Classgroup generated by hbm2java
 */
public class ClassGroup implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private Specialization specialization;
	private String name;
	private int yearOfStudy;
	private Teacher teacher ;
	private String specName;


	private Set<SubjectTeacherForClass> subjectteacherforclasses = new HashSet<SubjectTeacherForClass>(
			0);
	private List<Student> students = new ArrayList<Student>(0);
	private Set<AttendancesPerSubject> subjects = new HashSet<AttendancesPerSubject>(0);

	public ClassGroup() {
	}

	public ClassGroup(Specialization specialization, String name,
			int yearOfStudy) {
		this.specialization = specialization;
		this.name = name;
		this.yearOfStudy = yearOfStudy;
	}

	public ClassGroup(Specialization specialization, String name,
			int yearOfStudy, Teacher teacher,
			Set<SubjectTeacherForClass> subjectteacherforclasses,
			List<Student> students) {
		this.specialization = specialization;
		this.name = name;
		this.yearOfStudy = yearOfStudy;
		this.teacher = teacher;
		this.subjectteacherforclasses = subjectteacherforclasses;
		this.students = students;
	}

	public ClassGroup(String name, int yearOfStudy) {
		this.name = name;
		this.yearOfStudy = yearOfStudy;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Specialization getSpecialization() {
		return this.specialization;
	}

	public void setSpecialization(Specialization specialization) {
		this.specialization = specialization;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getYearOfStudy() {
		return this.yearOfStudy;
	}

	public void setYearOfStudy(int yearOfStudy) {
		this.yearOfStudy = yearOfStudy;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public Set<SubjectTeacherForClass> getSubjectteacherforclasses() {
		return this.subjectteacherforclasses;
	}

	public void setSubjectteacherforclasses(
			Set<SubjectTeacherForClass> subjectteacherforclasses) {
		this.subjectteacherforclasses = subjectteacherforclasses;
	}

	public List<Student> getStudents() {
		Collections.sort(students, new StudentComparator());
		return students;
	}

	public void setStudents(List<Student> students) {
		this.students = students;
	}

	public Set<AttendancesPerSubject> getAttendancespersubject() {
		return subjects;
	}

	public void setAttendancespersubject(Set<AttendancesPerSubject> subjects) {
		this.subjects = subjects;
	}
	public String getSpecName() {
		return specName;
	}

	public void setSpecName(String specName) {
		this.specName = specName;
	}
	@Override
	public boolean equals(Object obj) {
		if(obj==null)
		{
			return false;
		}
		if(!(obj instanceof ClassGroup))
		{
			return false;
		}
		
		ClassGroup that = (ClassGroup) obj;
		
		return that.name.equals(this.name) && that.yearOfStudy == this.yearOfStudy;
		
	}
}
