package com.catalog.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Studentmark generated by hbm2java
 */
public class StudentMark implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private SubjectTeacherForClass subjectTeacherForClass;
	private Student student;
	private int mark;
	private boolean finalExam;
	private boolean toBeDeleted;
	private Date date;
	private Semester semester;
	private Set<Logs> logs = new HashSet<Logs>(0);

	public StudentMark() {
	}

	public StudentMark(SubjectTeacherForClass subjectTeacherForClass,
			Student student, int mark, boolean finalExam, Date date) {
		this.subjectTeacherForClass = subjectTeacherForClass;
		this.student = student;
		this.mark = mark;
		this.finalExam = finalExam;
		this.date = date;
	}

	public StudentMark(SubjectTeacherForClass subjectTeacherForClass,
			Student student, int mark, boolean finalExam, Date date,
			Set<Logs> logs) {
		this.subjectTeacherForClass = subjectTeacherForClass;
		this.student = student;
		this.mark = mark;
		this.finalExam = finalExam;
		this.date = date;
		this.logs = logs;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public SubjectTeacherForClass getSubjectteacherforclass() {
		return this.subjectTeacherForClass;
	}

	public void setSubjectteacherforclass(
			SubjectTeacherForClass subjectTeacherForClass) {
		this.subjectTeacherForClass = subjectTeacherForClass;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public int getMark() {
		return this.mark;
	}

	public void setMark(int mark) {
		this.mark = mark;
	}

	public boolean isFinalExam() {
		return this.finalExam;
	}

	public void setFinalExam(boolean finalExam) {
		this.finalExam = finalExam;
	}

	public boolean isToBeDeleted() {
		return this.toBeDeleted;
	}

	public void setToBeDeleted(boolean toBeDeleted) {
		this.toBeDeleted = toBeDeleted;
	}

	public Semester getSemester() {
		return this.semester;
	}

	public void setSemester(Semester semester) {
		this.semester = semester;
	}

	public Set<Logs> getLogs() {
		return this.logs;
	}

	public void setLogs(Set<Logs> logs) {
		this.logs = logs;
	}

}
